[project]
name = "daily-arxiv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "arxiv>=2.1.3",
    "dotenv>=0.9.9",
    "langchain>=0.1.20",
    "scrapy>=2.12.0",
    #"langchain_zhipu>=4.1.8",
    "langchain-google-genai>=2.1.3",
    "lunr>=0.7.0",
]
